import { GoogleGenerativeAI } from "@google/generative-ai";
import axios from "axios";
import fs from "fs";
import path from "path";
import { config } from "../config";

const genAI = new GoogleGenerativeAI(config.gemini.apiKey);

export async function generateImage(prompt: string): Promise<string | null> {
  try {
    const imagesDir = config.paths.images;
    fs.mkdirSync(imagesDir, { recursive: true });

    // Use Gemini's Imagen REST API for image generation
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/imagen-4.0-generate-001:predict`,
      {
        instances: [
          {
            prompt: `Professional LinkedIn post image: ${prompt}. Clean, modern, minimalist design suitable for a professional social media feed.`,
          },
        ],
        parameters: {
          sampleCount: 1,
        },
      },
      {
        headers: {
          "Content-Type": "application/json",
          "x-goog-api-key": config.gemini.apiKey,
        },
      }
    );

    const predictions = response.data?.predictions;
    if (!predictions || predictions.length === 0 || !predictions[0].bytesBase64Encoded) {
      console.warn("No image generated by Gemini Imagen");
      return null;
    }

    const filename = `post-${Date.now()}.png`;
    const filepath = path.join(imagesDir, filename);
    const buffer = Buffer.from(predictions[0].bytesBase64Encoded, "base64");
    fs.writeFileSync(filepath, buffer);

    console.log(`Image generated: ${filepath}`);
    return filepath;
  } catch (err: any) {
    console.error(`Image generation failed: ${err.message}`);
    return null;
  }
}

export function shouldGenerateImage(): boolean {
  // Force image generation for testing — revert to: Math.random() * 100 < config.bot.imagePostPercentage
  return true;
}
